language: rust
cache: cargo
rust:
  - stable

before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

script:
  - cargo build --verbose --features ecc
  - cargo test --verbose --features ecc
