language: rust
cache: cargo
rust:
  - stable

env:
  global:
    - FEATURES=testing-utils

before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

script:
  - cargo build --features $FEATURES --verbose
  - cargo test --features $FEATURES --verbose
