[package]
name = "curv"
version = "0.2.3"
edition = "2018"

[lib]
crate-type = ["lib"]

[features]
default = ["rust-gmp"]
ec_secp256k1 = ["rust-gmp" ,"ecc", "secp256k1", "merkle"]
ec_ristretto = ["rust-gmp", "ecc" , "curve25519-dalek"]
ec_ed25519 = ["rust-gmp", "ecc" , "cryptoxide"]
ec_jubjub = ["rust-gmp", "ecc" , "pairing", "sapling-crypto"]
ecc = []
merkle = ["rust-crypto", "merkle-sha3"]

[dependencies]
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
zeroize = "0.10"
sha3 = "0.8.2"
sha2 = "0.8.0"
hmac = "0.7.1"
digest = "0.8.1"
hex = "^0.3"
blake2b_simd = "0.5.8"
lazy_static = "1.4"

[dependencies.rust-crypto]
version = "^0.2"
optional = true

[dependencies.merkle-sha3]
version = "^0.1"
optional = true

[dependencies.sapling-crypto]
git = "https://github.com/omershlo/librustzcash.git"
rev = "3e667406323430813f6dbae2a60b5a83046fa20a"
optional = true

[dependencies.pairing]
git = "https://github.com/omershlo/librustzcash.git"
rev = "3e667406323430813f6dbae2a60b5a83046fa20a"
optional = true

[dependencies.rust-gmp]
version = "0.5.0"
features = ["serde_support"]
git = "https://github.com/KZen-networks/rust-gmp"
optional = true

[dependencies.secp256k1]
version = "0.15.3"
features = ["serde"]
optional = true

[dependencies.curve25519-dalek]
version = "1.2.3"
optional = true

[dependencies.cryptoxide]
version = "0.1.2"
optional = true

[dev-dependencies]
bincode = "1.2.0"
serde_json = "1.0"
